---
output:
  pdf_document: default
  html_document: default
---
# What PandAna is for, and why we are designing PandAna 3

Starting from PandAna 2, the project goals have been the development of an easy-to-use  environment for fast and scalable analysis.
We achieve ease-of-use by the use of Python and Python data science tools (`numpy` and `pandas`).

PandAna 2 has support for parallel processing of data using MPI.
It does this in a manner that lets users almost entirely ignore any issues regarding MPI.
This is primarily done by arranging the reading of the HDF5 files to assure that data from a single event is never split across MPI ranks.
Because an analysis can treat event independently, this means user code never needs to communicate between MPI ranks.
The result is that the same code that works in a serial program will also work in a parallel program.

This program organization yields excellent (very nearly perfect) scaling properties for the in-memory processing portion of an analysis.
However, the reading performance becomes a limiting factor for relatively small MPI programs---those using a few hundred MPI ranks.
This is because good performance is obtained from the HDF5 reading only when the size of each dataset read by each rank is large.

The goal of PandAna 3 is to further the abilities of PandAna 2, to include automated MPI parallelism and high-performance IO (especially reading) of large data samples.
Furthermore, we are looking to redesign the internals of PandAna to allow the automatic optimization of workflows by scheduling both reading of data and evaluation of calculations in the most efficient fashion.

Our plans for re-design include introducing something like an *abstract syntax tree* (AST) to describe the "calculation" done in an analysis.
The calculation in question is the creation of a table of data (in HEP, often called an *ntuple*) to be used tasks such as the creation of histograms or other plots, the calculation of summary statistics, and for fitting.
We are introducing an AST to provide the opportunity to apply optimizations of the calculation before evaluation of the calculated result; the formal separation of the *creation* of the AST from its *evaluation*.
