@startuml
skinparam dpi 300

object "v2: SimpleVar" as var {
  table = "electrons"
  columns = ["pt"]
}

object "c1 : SimpleCut" as cut {
}

object "v1: SimpleVar" as met {
  table =  "events"
  columns = ["met"]
}

object "fv1: FilteredVar" as fv1 {
}

object "Callable" as pred {
 lambda df : df["met"] > 10
}

object "FilteredVar" as fv2 {
}

object "cut: SimpleCut" as cut2 {
}

object "var: SimpleVar" as hits {
  table = "electrons_hits"
  columns = ["e"]
}

object "Callable" as pred2 {
  lambda df: df["pt"] > 15
}

cut *-- met
cut *-- pred
fv1 *-- var
fv1 *-- cut

fv2 *-- hits
fv2 *-- cut2

cut2 *-- fv1
cut2 *-- pred2

@enduml
