@startuml
skinparam dpi 300

object "var: SimpleVar" as var {
  table = "electrons"
  columns = ["pt", "phi"]
}

object "cut: SimpleCut" as cut {
}

object "SimpleVar" as met {
  table =  "events"
  columns = ["met"]
}

object "FilteredVar" as fv {
}

object "Callable" as pred {
 lambda df : df["met"] > 10
}

cut *-- met
cut *-- pred
fv *-- var
fv *-- cut

@enduml
